server:
  port: 8000

spring:
  application:
    name: api-gateway-rest
  cloud:
    gateway:
      routes:
        - id: product-rest
          uri: http://localhost:8081
          predicates:
            - Path=/product-rest/**
        - id: offer-rest
          uri: http://localhost:8082
          predicates:
            - Path=/offer-rest/**