grpc:
  server:
    port: 9000

  client:
    grpc-product-service:
      address: static://localhost:9000
      negotiationType: plaintext


spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product-rest