server:
  port: 8182

spring:
  graphql:
    graphiql:
      enabled: true

  websocket:
    path: /graphql

  application:
    name: offer-rest
  data:
    mongodb:
      host: localhost
      port: 27017
      database: offer-rest