server:
    port: 8181


spring:
  graphql:
    graphiql:
      enabled: true

  websocket:
    path: /product-graphql

  application:
    name: product-graphql
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product-rest

