server:
  port: 8002

grpc:
  server:
    port: 9003

  client:
    grpc-product-service:
      address: static://product-grpc:9000
      negotiationType: plaintext

    grpc-offer-service:
      address: static://offer-grpc:9001
      negotiationType: plaintext


