server:
  port: 8000

spring:
  application:
    name: api-gateway-rest
  cloud:
    gateway:
      routes:
        - id: product-service-rest
          uri: http://product-service-rest:8081
          predicates:
            - Path=/product-rest/**
        - id: offer-service-rest
          uri: http://offer-service-rest:8082
          predicates:
            - Path=/offer-rest/**