server:
  port: 8086

grpc:
  server:
    port: 9001

  client:
    grpc-product-service:
      address: static://localhost:9000
      negotiationType: plaintext

    grpc-offer-client:
      address: static://localhost:9001
      negotiationType: plaintext


spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: offer-rest